version: "3.8"

services:
  
  # Database container
  db:
    container_name: db
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  # PgAdmin Container
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_DEFAULT_PASSWORD}
    depends_on:
      - db

  # The container for the fastapi
  api:
    container_name: api
    hostname: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    command: bash -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    container_name: web
    hostname: web
    build:
      context: ./web
      dockerfile: Dockerfile

volumes:
  postgres: